### PR TITLE
Code Spelling

### PR DESCRIPTION
**Pull request by clarkmoody**
Changes occurrences of "it's" to "its" where appropriate within the project code.

My editor removed whitespace from line endings as well.

### CODE REVIEW

**Comment by peter-conalgo** [comment]
I'm okay with fixing spelling mistakes, but the massive whitespace changes are a problem. Could you try again, but control your editor this time? Thanks!

**Comment by clarkmoody** [comment]
Whitespace is only changing at line-ending, which is thrown away by interpreter / compiler anyway. No additional newlines or indentation changes involved.

**Comment by clarkmoody** [comment]
#5 preserves whitespace as requested.

**Comment by peter-conalgo** [comment]
Superseded by pull #5

**Pull request closed without merging**
