### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lucaszanella**
adds compilation instructions for ubuntu 20.04 (minimal installation)

couldn't use the instructions on my clean ubuntu 20.04 (minimal setup installation) vm so I updated with all things I did for it to work

### CODE REVIEW

**Comment by lucaszanella** [comment]
PS: when compiling firmware:

```
(ENV) lz@vm:~/firmware/stm32$ make setup && make; make firmware-signed.dfu
cd ../external/micropython ; git submodule update --init lib/stm32lib
cd ../external/micropython/mpy-cross ; make
make[1]: Entering directory '/home/lz/firmware/external/micropython/mpy-cross'
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
make[1]: Leaving directory '/home/lz/firmware/external/micropython/mpy-cross'
ln -s ../external/micropython/ports/stm32 l-port
ln: failed to create symbolic link 'l-port/stm32': File exists
make: [Makefile:204: setup] Error 1 (ignored)
ln -s ../external/micropython l-mpy
ln: failed to create symbolic link 'l-mpy/micropython': File exists
make: [Makefile:205: setup] Error 1 (ignored)
cd ../external/micropython/ports/stm32/boards ; ln -s ../../../../../stm32/COLDCARD COLDCARD
ln: failed to create symbolic link 'COLDCARD/COLDCARD': File exists
make: [Makefile:206: setup] Error 1 (ignored)
cd ../external/micropython/ports/stm32 && make BOARD=COLDCARD -j 4
make[1]: Entering directory '/home/lz/firmware/external/micropython/ports/stm32'
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
boards/COLDCARD/mpconfigboard.mk:54: *** missing separator.  Stop.
make[1]: Leaving directory '/home/lz/firmware/external/micropython/ports/stm32'
make: *** [Makefile:17: all] Error 2
make: *** No rule to make target 'l-port/build-COLDCARD/firmware?.bin', needed by 'firmware-signed.bin'.  Stop.
```

otherwise I'd be able to test the firmware and add this step

**Comment by lucaszanella** [comment]
Fixed previous error. Now this:

```
In file included from ../../lib/stm32lib/CMSIS/STM32L4xx/Include/stm32l475xx.h:183,
                 from ../../lib/stm32lib/CMSIS/STM32L4xx/Include/stm32l4xx.h:150,
                 from ../../lib/stm32lib/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_def.h:48,
                 from ../../lib/stm32lib/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_rcc.h:47,
                 from boards/COLDCARD/stm32l4xx_hal_conf.h:194,
                 from ../../lib/stm32lib/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal.h:48,
                 from ./mpconfigboard_common.h:30,
                 from ./boards/COLDCARD/ckcc-port.h:39,
                 from ../../py/mpconfig.h:43,
                 from ../../py/obj.h:29,
                 from modmachine.h:29,
                 from modmachine.c:30:
modmachine.c: In function 'machine_bootloader':
../../lib/cmsis/inc/core_cm4.h:93:28: error: listing the stack pointer register 'sp' in a clobber list is deprecated [-Werror=deprecated]
   93 |   #define __ASM            __asm                                      /*!< asm keyword for GNU Compiler */
      |                            ^~~~~

```

which is fixable by adding

`CFLAGS += -Wno-error=deprecated`

on

`external/micropython/ports/stm32/Makefile`

but then we get

```
CC spibdev.c
arm-none-eabi-gcc -DMP_CONFIGFILE=\"boards/COLDCARD/ckcc-port.h\" -I. -I../.. -Ibuild-COLDCARD -I../../lib/cmsis/inc -I../../lib/stm32lib/CMSIS/STM32L4xx/Include/ -I../../lib/stm32lib/STM32L4xx_HAL_Driver/Inc -Iusbdev/core/inc -Iusbdev/class/inc -I../../lib/lwip/src/include -Ilwip_inc -Wall -Wpointer-arith -Werror -std=gnu99 -nostdlib -Iboards/COLDCARD/modcryptocurrency -Iboards/COLDCARD/crypto -DVECT_TAB_OFFSET=0x8000 -DFFCONF_H=\"lib/oofatfs/ffconf.h\"  -DSTM32L475xx -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mtune=cortex-m4 -mcpu=cortex-m4 -g -Os -DNDEBUG -Iboards/COLDCARD -DSTM32_HAL_H='<stm32l4xx_hal.h>' -DMICROPY_HW_VTOR=0x08008000 -DMICROPY_FLOAT_IMPL=MICROPY_FLOAT_IMPL_FLOAT -fsingle-precision-constant -Wdouble-promotion -fdata-sections -ffunction-sections -Wno-error=deprecated -DMICROPY_QSTR_EXTRA_POOL=mp_qstr_frozen_const_pool -DMICROPY_MODULE_FROZEN_MPY -c -MD -o build-COLDCARD/spibdev.o spibdev.c
flashbdev.c: In function 'flash_bdev_writeblock':
flashbdev.c:266:5: error: 'memcpy' forming offset [1, 512] is out of the bounds [0, 0] of object '_ram_fs_cache_start' with type 'uint8_t[]' [-Werror=array-bounds]
  266 |     memcpy(dest, src, FLASH_BLOCK_SIZE);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
flashbdev.c:102:16: note: '_ram_fs_cache_start' declared here
  102 | extern uint8_t _ram_fs_cache_start[0];      // size determined by linker file
      |                ^~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

```

which since is a bound error I think it should not be ignored.

I'm not an specialist just wanted to test the emulator and see how the wallet works

What you say?

**Comment by lucaszanella** [comment]
Now I noticed `// size determined by linker file`. I think we can ignore this error then? The problem is that we'd ignore all bound errors for other memcpy...

**Comment by peter-conalgo** [comment]
Thanks for these changes to the README ... the Makefile changes are going to get lost because we are revamping the entire build system for v4 (unpublished branch right now).

**Comment by lucaszanella** [comment]
@peter-conalgo ok thanks, just for completeness:

`CFLAGS += -Wno-error=deprecated -Wno-error=array-bounds -Wno-error=vla-larger-than= -Wno-error=attributes`

on `external/micropython/ports/stm32/Makefile`

and doing `sudo ln -s /usr/bin/python3 /usr/bin/python` 

makes the firmware compile, but I don't think it should be recommended because some ubuntu people might use python2 for some things. The file `../external/micropython/tools/dfu.py` tried to launch python2 with the shebang `#!/usr/bin/python`. This should be fixed instead. 

My last error is on moving the firmware:

```
(ENV) lz@vm:~/firmware/stm32$ ckcc upgrade firmware-signed.dfu
Traceback (most recent call last):
  File "/home/lz/firmware/ENV/bin/ckcc", line 8, in <module>
    sys.exit(main())
  File "/home/lz/firmware/ENV/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/lz/firmware/ENV/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/lz/firmware/ENV/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lz/firmware/ENV/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lz/firmware/ENV/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/lz/firmware/ENV/lib/python3.8/site-packages/ckcc/cli.py", line 275, in firmware_upgrade
    real_file_upload(filename, do_upgrade=True, do_reboot=(not stop_early))
  File "/home/lz/firmware/ENV/lib/python3.8/site-packages/ckcc/cli.py", line 177, in real_file_upload
    dev = dev or ColdcardDevice(sn=force_serial)
  File "/home/lz/firmware/ENV/lib/python3.8/site-packages/ckcc/client.py", line 50, in __init__
    raise KeyError("Could not find Coldcard!" 
KeyError: 'Could not find Coldcard!'

```

**Comment by lucaszanella** [comment]
I thought compiling the firmware was needed but apparently it was an instruction for sending it to coldcard if needed. Anyway, when I launch the simulator:
Screenshot from 2021-02-21 15-01-43

**Comment by lucaszanella** [comment]
Sorry, I think virtualenv clear everything I done yesterday now that I opened it again. I've runned it but buttons won't work and it says this message forever

Screenshot from 2021-02-21 15-05-18

**Comment by lucaszanella** [comment]
PS: doing

```
        # If on linux, try commenting the following line
        #addr = bytes([len(fn)+2, socket.AF_UNIX] + list(fn))
        # If on linux, try uncommenting the following two lines
        import struct
        addr = struct.pack('H108s', socket.AF_UNIX, fn)
```

didn't help

**Comment by lucaszanella** [comment]
Ok, rebuilding everything worked.

PS: `libtool` also must be installed on ubuntu using `sudo apt-get install -y libtool`

**Comment by lucaszanella** [comment]
I made a dockerized version: https://github.com/lucaszanella/coldcard-docker

However sometimes it opens with the screen showing glitches or simply crashes. Simply running 2 or 3 times again launches a working coldcard.

Hope it helps people that want to test.

Gonna try to find out the problem, probably driver related and probably wouldn't happen on other computers

Screenshot from 2021-02-21 16-39-41

**Comment by lucaszanella** [comment]
On both the simulator and dockerized simulator I get ENOENT when trying to write to micro SD, would be cool to be able to test it fully. Is this linux-specific?

**Comment by lucaszanella** [comment]
@peter-conalgo 

Found the error.

On https://github.com/Coldcard/firmware/blob/master/unix/frozen-modules/ffilib.py#L17 it tried to detect sys.firmware, but even on linux, somehow this is valued `coldcard-unix`. Changing this line by

        if sys.platform == "linux" or sys.platform == "coldcard-unix" :

fixes, microSD works, but I bet this is not what you want because then on macOS it'd also be `coldcard-unix` and thus it would try to open a `.so`. 

So I propose

       if sys.platform == "linux" or os.getenv('COLDCARD_LINUX')=='1':

and of course 

`import os`

on the first line

Then the instructions say that we should set 

       export COLDCARD_LINUX=1

for linux.

I think there's no way to change `coldcar-unix` because it's defined on `unix/mpconfigport_coldcard.h`:

`#define MICROPY_PY_SYS_PLATFORM "coldcard-unix"`

**Comment by lucaszanella** [comment]
I wanted to test the multisig but apparently all instances of the wallet that I run have the same private key, even if I erase it. 

Can someone please tell me how to get a different private key for one coldcard simulator?

I done all those fixes to test the multisig :)

**Comment by peter-conalgo** [comment]
Best approach is to use BIP 39 pass phrase. Lots of this in the test cases using “Me”, “Myself” and similar.

**Comment by lucaszanella** [comment]
@peter-conalgo sorry don't know what you're talking about, but I discovered that

`./simulator.py -w`

makes it run without any keys so I can create one.

Using this worked and I was able to create multisig between 2 coldcard devices on testnet.

Please consider https://github.com/Coldcard/firmware/pull/64#issuecomment-782935526

**Pull request closed without merging**
