### PR TITLE
Block User management commands and HSM related commands if not explicitly enabled

### PR DESCRIPTION
**Pull request by scgbckbone**

### CODE REVIEW

**Comment by doc-hex** [comment]
afterthought: maybe we should enable these commands automatically, when an HSM config is imported?

**Comment by scgbckbone** [comment]
updated

**Comment by doc-hex** [comment]
Question: Will this work w/ "boot to HSM" feature and/or system where HSM was in use in previous firmware version?
I think we should force the new config value to True, if evidence HSM was on previous during upgrade process or first start after upgrade.

**Comment by scgbckbone** [comment]
@straylight-orbit I would consider 1. and 2. to be just one step with confirmation. With my latest addition if your policy file is already there - you do not need to do any extra step after you upgrade to version with this PR code

**Pull request merged**
