### PR TITLE
improved addr explorer

### PR DESCRIPTION
**Pull request by switck**
- can do sub-accounts now, just enter the number
- can hide warning after reading first time (press 6)
- can do custom derivation paths
- can do multisig wallets

ur licenses are all over the map, so if it helps I disclaim all copyright on this. consider it a gift

### CODE REVIEW

**Comment by peter-conalgo** [comment]
Thanks for this code! Looks really useful, but is there test code to match?

**Comment by switck** [comment]
free code == "it works for me"

**Comment by peter-conalgo** [comment]
I will add test cases and do some cleanup. It's on branch "better-ax" on this repo.

**Comment by nvk** [comment]
Thanks again for contributing.

**Pull request merged**
