### PR TITLE
Fix USB framing bug

### PR DESCRIPTION
**Pull request by ghost**
There is a problem with USB framing when handling errors.

1. Inner framing errors weren't floated up for the outer handler to handle so they were handled as generic exceptions.
2. `framing_error` wasn't setting the final (`0x80`) flag on the first byte and that would confuse the other end of the wire and cause it to expect more packets.

The `framing_error` function was rewritten to be more sensible and readable.

If this is accepted, I'll open another PR to port this to the v4 firmware.

### CODE REVIEW

**Comment by Terry330** [comment]
Want to sell out my coin

**Comment by Terry330** [comment]
Great

**Comment by Kenny7213** [comment]
Can I please have someone contact me to possibly answer a few general
questions I have? I would honestly appreciate you greatly if anyone would
be willing. I have about 95k in tron/usdt but I can't acc3ss the wallet and
its beyond frustrating. I would happily compensate for any progress made
directly from your assistance.

**Comment by Terry330** [comment]
Contact me directly

**Pull request closed without merging**
